import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface InspectionForExport {
  inspection_no?: string
  inspection_date?: string
  project_name?: string
  factory_name?: string
  auditor_name?: string
  auditor_type?: string
  category?: string
  sample_size?: number
  lot_size?: number
  aql_level?: string
  aql_result?: string
  inspector_decision?: string
  inspector_comments?: string
  critical_defects?: number
  major_defects?: number
  minor_defects?: number
  critical_allowed?: number
  major_allowed?: number
  minor_allowed?: number
}

interface DefectForExport {
  defect_name?: string
  severity?: string
  location?: string
  source?: string
  quantity?: number
}

export function exportInspectionPDF(inspection: InspectionForExport, defects: DefectForExport[] = []): void {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(18)
  doc.setTextColor('#BA7517')
  doc.text('SankalpHub', 14, 18)
  doc.setFontSize(9)
  doc.setTextColor('#999')
  doc.text('Inspection Report', 14, 25)

  // Result banner
  const isPassed = inspection.aql_result === 'pass'
  doc.setFontSize(16)
  doc.setTextColor(isPassed ? '#1D9E75' : '#E24B4A')
  doc.text(isPassed ? '\u2713 PASSED' : '\u2717 FAILED', 14, 40)

  // Inspection details table
  autoTable(doc, {
    startY: 48,
    head: [['Field', 'Details']],
    body: [
      ['Inspection ID', inspection.inspection_no || '\u2014'],
      ['Date', inspection.inspection_date || '\u2014'],
      ['Project', inspection.project_name || '\u2014'],
      ['Factory', inspection.factory_name || '\u2014'],
      ['Inspector', `${inspection.auditor_name || '\u2014'} \u00B7 ${inspection.auditor_type || ''}`.trim()],
      ['Category', inspection.category || '\u2014'],
      ['Sample size', `${inspection.sample_size || 0} / ${inspection.lot_size || 0} pcs`],
      ['AQL Level', inspection.aql_level || '\u2014'],
      ['Result', (inspection.aql_result || 'pending').toUpperCase()],
      ['Decision', inspection.inspector_decision || '\u2014'],
    ],
    headStyles: { fillColor: [186, 117, 23] },
  })

  // AQL summary
  const y = (doc as any).lastAutoTable.finalY + 10
  autoTable(doc, {
    startY: y,
    head: [['Severity', 'Found', 'Allowed', 'Result']],
    body: [
      ['Critical', String(inspection.critical_defects ?? 0), '0',
        (inspection.critical_defects ?? 0) === 0 ? 'PASS' : 'FAIL'],
      ['Major', String(inspection.major_defects ?? 0), `\u2264${inspection.major_allowed ?? 7}`,
        (inspection.major_defects ?? 0) <= (inspection.major_allowed ?? 7) ? 'PASS' : 'FAIL'],
      ['Minor', String(inspection.minor_defects ?? 0), `\u2264${inspection.minor_allowed ?? 14}`,
        (inspection.minor_defects ?? 0) <= (inspection.minor_allowed ?? 14) ? 'PASS' : 'FAIL'],
    ],
    headStyles: { fillColor: [186, 117, 23] },
  })

  // Defect list
  if (defects.length > 0) {
    const y2 = (doc as any).lastAutoTable.finalY + 10
    doc.setFontSize(12)
    doc.setTextColor('#111')
    doc.text('Defect Details', 14, y2)
    autoTable(doc, {
      startY: y2 + 6,
      head: [['Defect Name', 'Severity', 'Location', 'Source', 'Qty']],
      body: defects.map(d => [
        d.defect_name || '\u2014', d.severity || '\u2014',
        d.location || '\u2014', d.source || 'manual', String(d.quantity ?? 1),
      ]),
      headStyles: { fillColor: [186, 117, 23] },
    })
  }

  // Comments
  if (inspection.inspector_comments) {
    const y3 = (doc as any).lastAutoTable.finalY + 10
    doc.setFontSize(10)
    doc.setTextColor('#333')
    doc.text('Inspector Comments', 14, y3)
    doc.setFontSize(9)
    doc.setTextColor('#666')
    doc.text(inspection.inspector_comments, 14, y3 + 7, { maxWidth: 180 })
  }

  // Footer
  doc.setFontSize(7)
  doc.setTextColor('#bbb')
  doc.text('Generated by SankalpHub \u2014 sankalphub.in', 14, 285)

  doc.save(`${inspection.inspection_no || 'inspection'}-report.pdf`)
}
