import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface ProjectForExport {
  name: string
  season?: string | null
  product_category?: string | null
  product_type?: string | null
  factory_name?: string | null
  po_number?: string | null
  quantity?: number | null
  unit?: string | null
  country?: string | null
  buyer_brand?: string | null
  status?: string | null
  priority?: string | null
  aql_level?: string | null
  inspection_type?: string | null
  expected_delivery?: string | null
  deadline?: string | null
  inspection_date?: string | null
  shipment_date?: string | null
  sizes?: Record<string, string | number> | null
  notes?: string | null
}

export function exportProjectPDF(project: ProjectForExport): void {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor('#BA7517')
  doc.text('SankalpHub', 14, 20)
  doc.setFontSize(10)
  doc.setTextColor('#888')
  doc.text('Production Intelligence Platform', 14, 27)

  // Project title
  doc.setFontSize(16)
  doc.setTextColor('#111')
  doc.text(project.name, 14, 42)

  doc.setFontSize(10)
  doc.setTextColor('#666')
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 14, 50)

  // Project details table
  autoTable(doc, {
    startY: 58,
    head: [['Field', 'Details']],
    body: [
      ['Project Name', project.name],
      ['Season', project.season || '\u2014'],
      ['Category', project.product_category || '\u2014'],
      ['Product Type', project.product_type || '\u2014'],
      ['Factory', project.factory_name || '\u2014'],
      ['PO Number', project.po_number || '\u2014'],
      ['Quantity', project.quantity ? `${project.quantity.toLocaleString()} ${project.unit || 'pcs'}` : '\u2014'],
      ['Country', project.country || '\u2014'],
      ['Buyer / Brand', project.buyer_brand || '\u2014'],
      ['Status', project.status || '\u2014'],
      ['Priority', project.priority || '\u2014'],
      ['AQL Level', project.aql_level || '\u2014'],
      ['Inspection Type', project.inspection_type || '\u2014'],
      ['Expected Delivery', project.expected_delivery || project.deadline || '\u2014'],
      ['Inspection Date', project.inspection_date || '\u2014'],
      ['Shipment Date', project.shipment_date || '\u2014'],
    ],
    headStyles: { fillColor: [186, 117, 23] },
    alternateRowStyles: { fillColor: [250, 250, 248] },
  })

  // Size breakdown
  const sizes = project.sizes || {}
  const sizeEntries = Object.entries(sizes).filter(([, v]) => v && parseInt(String(v)) > 0)
  if (sizeEntries.length > 0) {
    const currentY = (doc as any).lastAutoTable.finalY + 10
    doc.setFontSize(12)
    doc.setTextColor('#111')
    doc.text('Size Breakdown', 14, currentY)
    autoTable(doc, {
      startY: currentY + 6,
      head: [sizeEntries.map(([k]) => k)],
      body: [sizeEntries.map(([, v]) => String(v))],
      headStyles: { fillColor: [201, 169, 110] },
    })
  }

  // Notes
  if (project.notes) {
    const notesY = (doc as any).lastAutoTable.finalY + 10
    doc.setFontSize(12)
    doc.setTextColor('#111')
    doc.text('Notes', 14, notesY)
    doc.setFontSize(10)
    doc.setTextColor('#666')
    doc.text(project.notes, 14, notesY + 8, { maxWidth: 180 })
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor('#aaa')
  doc.text('Generated by SankalpHub \u2014 sankalphub.in', 14, 285)

  doc.save(`${project.name.replace(/\s+/g, '-')}-project.pdf`)
}
